### ISSUE TITLE
Release 0.6.0 checklist

### ISSUE THREAD

**Issue by qmhu** [gocrane/crane#398]
- [x] Prediction with custom/external metric for EHPA, including code change and doc @qmhu 
- [ ]  QoS Ensurance, including code change and doc @chenkaiyue 
- [x] DSP algo improvement, including code change and doc @yufeiyu
