### ISSUE TITLE
Crane Dashboard TODO

### ISSUE THREAD

**Issue by zsnmwy** [gocrane/crane#453]
The crane dashboard is still empty. 
Therefore, we need to complete the below tasks to fill it.

### Global
- [x] #471
- [x] #475
- [ ] We need to use Math.js to avoid the accuracy of floating point calculations.

### Charts components based on ECharts

The charts data fetch from Prometheus with PromQL (Prometheus Query Language).
- [x] [series-line](https://echarts.apache.org/en/option.html#series-line)
- [x] [series-pie](https://echarts.apache.org/en/option.html#series-pie)
- [ ] [Bubble Chart](https://echarts.apache.org/examples/en/editor.html?c=bubble-gradient)

### Dashboard
- [x] metrics display

### Cost Insight

- Cost display group by multiple dimensions
   - [x] Request Usage panel
   - [x] Cost panel
   - [x] Carbon Emission panel
   - [ ] Maturity panel
- [x] Rename “成本大师 “to “成本洞察”
- [ ] Jump to different pages based on the cost items.

### Workload Optimize
- [ ] Use [Bubble Chart](https://echarts.apache.org/examples/zh/editor.html?c=scatter-aqi-color) to show the Request Resource spec distribution and Recommend Resource spec distribution.
- [ ] Graphical representation of the difference between Request Resource and Recommendation Resource for each workload.
- [x] Local Table Pagination
- [x] Search
- [ ] Sort Data
- [x] Some fields may need to change
- [ ] #503
- [ ] #504

### EHPA

- [ ] TimeSeriesPrediction

### Cluster Optimize
- [ ] Waterline Management

### Management Center
- [x] Add Cost Management
- [x] Discount Management
