### ISSUE TITLE
Release 0.9.0 checklist

### ISSUE THREAD

**Issue by qmhu** [gocrane/crane#640]
- [ ] Crane-Agent install in Installation docs, show the limitation for agent @chenkaiyue 
- [x] Don't create tsp in default chart install @chenkaiyue 
- [x] Release deploy testing @qmhu
